# This makefile holds "end-to-end" tests, i.e. function usage with kpt and real manifest manipulation

FN_MODE ?= exec

ifeq ($(CONTAINER_TAG),)
APPLY_SETTERS_IMAGE := ghcr.io/krm-functions/apply-setters@sha256:88b3c3d1a02b7ddb791fb3c868d69b3c35a9969794da6f76be9678f8e6673fe7
DIGESTER_IMAGE := ghcr.io/krm-functions/digester@sha256:1402287ad022b5922271f72ada13fab75addd79d2a3dcbadd22daea762b1b029
HELM_RENDER_IMAGE := ghcr.io/krm-functions/render-helm-chart@sha256:f559896b26240ddea78db207e2842940b70de750dc9f676a0332433f9b3ec4c4
HELM_SOURCE_IMAGE := ghcr.io/krm-functions/source-helm-chart@sha256:1a1d4acbe03050f949c2921ef358a98b07b6325af9ff8632a013a3a0cb8ed157
HELM_UPGRADER_IMAGE := ghcr.io/krm-functions/helm-upgrader@sha256:62659f1de87537b51b99419e6e64fa540b16e699a77e9f7b2f5282c5a2e65f04
KUBECONFORM_IMAGE := ghcr.io/krm-functions/kubeconform@sha256:c41653293c6075c94eee05df4194d0911bf53bd7d057dc368d34f995e6ac5dbb
PACKAGE_COMPOSITOR_IMAGE := ghcr.io/krm-functions/package-compositor@sha256:b5f0074ced2f24286dd4962c1e2c150364f1bf6c50f615497bd53fd5f7d506a4
SET_LABELS_IMAGE := ghcr.io/krm-functions/set-labels@sha256:123abc
else
APPLY_SETTERS_IMAGE := ghcr.io/krm-functions/apply-setters:$(CONTAINER_TAG)
DIGESTER_IMAGE := ghcr.io/krm-functions/digester:$(CONTAINER_TAG)
HELM_RENDER_IMAGE := ghcr.io/krm-functions/render-helm-chart:$(CONTAINER_TAG)
HELM_SOURCE_IMAGE := ghcr.io/krm-functions/source-helm-chart:$(CONTAINER_TAG)
HELM_UPGRADER_IMAGE := ghcr.io/krm-functions/helm-upgrader:$(CONTAINER_TAG)
KUBECONFORM_IMAGE := ghcr.io/krm-functions/kubeconform:$(CONTAINER_TAG)
PACKAGE_COMPOSITOR_IMAGE := ghcr.io/krm-functions/package-compositor:$(CONTAINER_TAG)
SET_LABELS_IMAGE := ghcr.io/krm-functions/set-labels:$(CONTAINER_TAG)
endif

ifeq ($(FN_MODE),exec)
APPLY_SETTERS := --exec bin/linux_amd64/apply-setters
DIGESTER := --exec bin/linux_amd64/digester
HELM_RENDER := --exec bin/linux_amd64/render-helm-chart
HELM_SOURCE := --exec bin/linux_amd64/source-helm-chart
HELM_UPGRADER := --exec bin/linux_amd64/helm-upgrader
KUBECONFORM := --exec bin/linux_amd64/kubeconform
TEMPLATE_KYAML := --exec bin/linux_amd64/template-kyaml
PACKAGE_COMPOSITOR := --exec bin/linux_amd64/package-compositor
SET_LABELS := --exec bin/linux_amd64/set-labels
else
APPLY_SETTERS := --image $(APPLY_SETTERS_IMAGE)
DIGESTER := --network --image $(DIGESTER_IMAGE)
HELM_RENDER := --network --image $(HELM_RENDER_IMAGE)
HELM_SOURCE := --network --image $(HELM_SOURCE_IMAGE)
HELM_UPGRADER := --network --image $(HELM_UPGRADER_IMAGE)
KUBECONFORM := --network --image $(KUBECONFORM_IMAGE)
PACKAGE_COMPOSITOR := --network --image $(PACKAGE_COMPOSITOR_IMAGE)
SET_LABELS := --network --image $(SET_LABELS_IMAGE)
endif

BASELINE_RENDER_HELM_CHART := gcr.io/kpt-fn/render-helm-chart:v0.2.2

e2e-tests: test-render-helm-chart \
	   render-helm-chart-example \
	   render-helm-chart-example2 \
	   render-with-kube-version \
	   test-source-helm-chart \
	   test-helm-upgrader \
	   test-apply-setters \
	   test-digester \
	   test-kubeconform \
	   test-package-compositor-e2e

# BEWARE: These tests are fragile - we want to test upgrades, but without upgrade-constraints tests might fail when charts are updated
.PHONY: test-helm-upgrader
test-helm-upgrader:
	rm -rf tmp-results
	kpt fn source examples/helm-upgrader | kpt fn eval - --fn-config example-function-configs/config-upgrade-helm-version-inline.yaml --truncate-output=false --results-dir tmp-results $(HELM_UPGRADER) > test-out.txt
	grep -e '.*upgrade-available: .*cert-manager:v1.8.2' test-out.txt
	grep -e '.*upgrade-available.0: .*cert-manager:v1.12.1' test-out.txt
	grep -e '.*upgrade-available.0: .*metacontroller-helm:v4.10.0' test-out.txt
	grep -e '.*upgrade-available.0: .*karpenter:0.35.0' test-out.txt
	grep -e '.*upgrade-available.1: .*/external-secrets:0.14.0' test-out.txt
	rm test-out.txt
	rm -rf tmp-results

.PHONY: test-render-helm-chart
test-render-helm-chart:
	# For reference, render chart using baseline function
	rm -rf rendered-output
	echo "" | kpt fn eval - --network --fn-config examples/render-helm-chart2/argo-workflows.yaml -i ${BASELINE_RENDER_HELM_CHART} | kpt fn sink rendered-output
	# Source step, fetch chart from upstream, but do not render
	rm -rf sourced-output
	kpt fn source examples/render-helm-chart2 | kpt fn eval - ${HELM_RENDER} --results-dir results2 | kpt fn sink sourced-output
	grep -e 'message: sourcing with render-helm-chart is deprecated' results2/results.yaml
	# Render from previously sourced chart
	rm -rf rendered-output2
	kpt fn source sourced-output | kpt fn eval - ${HELM_RENDER} | kpt fn sink rendered-output2
	diff -q rendered-output rendered-output2
	rm -rf rendered-output sourced-output rendered-output2 results2

# Example usage from docs/render-helm-chart.md
.PHONY: render-helm-chart-example
render-helm-chart-example:
	kpt fn source examples/render-helm-chart | kpt fn eval - ${HELM_SOURCE} | kpt fn sink my-cert-manager-package
	grep -q 'apiVersion: experimental.helm.sh/v1alpha1' my-cert-manager-package/cert-manager-chart.yaml
	cp examples/render-helm-chart/Kptfile my-cert-manager-package/
	kpt fn render my-cert-manager-package -o stdout | grep -q 'team-name: blue-team'
	rm -rf my-cert-manager-package

.PHONY: render-helm-chart-example2
render-helm-chart-example2:
	kpt fn source examples/render-helm-chart/non-stardard-tar-filename | kpt fn eval - ${HELM_RENDER} | kpt fn sink my-non-stardard-tar-filename
	rm -rf my-non-stardard-tar-filename

# Test rendering using Capabilities.KubeVersion
.PHONY: render-with-kube-version
render-with-kube-version:
	mkdir _tmp
	helm package test-data/test-chart
	scripts/source-chart.sh test-data/render-test-chart.yaml test-chart-0.1.0.tgz > _tmp/render.yaml
	rm test-chart-0.1.0.tgz
	# Note, no patch version
	sed -i 's/kubeVersion: .*/kubeVersion: 1.29/' _tmp/render.yaml
	kpt fn source _tmp | kpt fn eval - ${HELM_RENDER} | kpt fn sink _tmp-output
	cat _tmp-output/configmap_foo.yaml
	grep -q 'kubeVersion: "v1.29.0"' _tmp-output/configmap_foo.yaml
	grep -q 'kubeVersionMinor: "29"' _tmp-output/configmap_foo.yaml
	rm -rf _tmp-output
	sed -i 's/kubeVersion: .*/kubeVersion: 1.30.0/' _tmp/render.yaml
	kpt fn source _tmp | kpt fn eval - ${HELM_RENDER} | kpt fn sink _tmp-output
	cat _tmp-output/configmap_foo.yaml
	grep -q 'kubeVersion: "v1.30.0"' _tmp-output/configmap_foo.yaml
	grep -q 'kubeVersionMinor: "30"' _tmp-output/configmap_foo.yaml
	rm -rf _tmp _tmp-output

.PHONY: test-source-helm-chart
test-source-helm-chart:
	kpt fn source examples/render-helm-chart3 | kpt fn eval - --truncate-output=false $(HELM_SOURCE) > test-out.txt
	grep -e 'experimental.helm.sh/chart-sum/karpenter' test-out.txt
	grep -e 'experimental.helm.sh/chart-sum/cert-manager' test-out.txt
	rm test-out.txt

.PHONY: test-apply-setters
test-apply-setters: test-apply-setters1 test-apply-setters2

.PHONY: test-apply-setters1
test-apply-setters1:
	kpt fn source examples/apply-setters | kpt fn eval - --truncate-output=false $(APPLY_SETTERS) --fn-config example-function-configs/apply-setters/cm-setters.yaml | kpt fn eval - -i gcr.io/kpt-fn/remove-local-config-resources:v0.1.0 -o unwrap > test-out.txt
	grep -e 'foo: "valueFoo"' test-out.txt
	grep -e 'bar: "valueBar"' test-out.txt
	grep -e 'baz: "valueBaz"' test-out.txt
	grep -e 'replicas: "4"' test-out.txt
	grep -e 'combined: ""' test-out.txt
	grep -e 'app.kubernetes.io/version: "a1b2c3d4e5e6"' test-out.txt
	rm test-out.txt

.PHONY: test-apply-setters2
test-apply-setters2:
	kpt fn source examples/apply-setters | kpt fn eval - --truncate-output=false $(APPLY_SETTERS) --fn-config example-function-configs/apply-setters/apply-setters-fn-config.yaml | kpt fn eval - -i gcr.io/kpt-fn/remove-local-config-resources:v0.1.0 -o unwrap > test-out.txt
	grep -e 'foo: ""' test-out.txt
	grep -e 'bar: "valueBar2"' test-out.txt
	grep -e 'baz: "valueBaz2"' test-out.txt
	grep -e 'replicas: "4"' test-out.txt
	grep -e 'combined: "4-a1b2c3d4e5e6"' test-out.txt
	grep -e 'app.kubernetes.io/version: "a1b2c3d4e5e6"' test-out.txt
	rm test-out.txt

.PHONY: test-digester
test-digester: test-digester-step1 test-digester-step3 test-digester-output

.PHONY: test-digester-step1
test-digester-step1:
	rm -rf digester-tmp0
	kpt fn source examples/digester | kpt fn eval - --truncate-output=false $(HELM_SOURCE) | kpt fn sink digester-tmp0

.PHONY: test-digester-step2
test-digester-step2:
	kpt fn source digester-tmp0 | kpt fn eval - --truncate-output=false $(DIGESTER) > test-out.txt
	head -n 60 test-out.txt

.PHONY: test-digester-step3
test-digester-step3:
	rm -rf digester-tmp1
	kpt fn source digester-tmp0 | kpt fn eval - --truncate-output=false $(DIGESTER) | kpt fn sink digester-tmp1
	kpt fn render digester-tmp1 -o unwrap > test-out.yaml

.PHONY: test-digester-output
test-digester-output:
	grep 'image: "quay.io/jetstack/cert-manager-controller@sha256:.*' test-out.yaml
	grep 'image: "quay.io/jetstack/cert-manager-cainjector@sha256:.*' test-out.yaml
	grep 'image: "quay.io/jetstack/cert-manager-webhook@sha256:.*' test-out.yaml
	grep 'image: "quay.io/jetstack/cert-manager-ctl@sha256:.*' test-out.yaml

.PHONY: test-digester-w-containers
test-digester-w-containers:
	echo "** sourcing step"
	rm -rf cert-manager-package
	kpt fn source examples/digester \
	  | kpt fn eval - $(HELM_SOURCE) \
	  | kpt fn eval - --truncate-output=false $(DIGESTER) \
	  | kpt fn sink cert-manager-package

.PHONY: test-digester-w-containers2
test-digester-w-containers2:
	echo "** rendering using pipeline in Ktfile"
	rm -rf cert-manager-rendered
	kpt fn render cert-manager-package -o stdout | kpt fn sink cert-manager-rendered

#KUBECONFORM_SCHEMA_LOCATIONS ?= "default"
KUBECONFORM_SCHEMA_LOCATIONS ?= 'examples/kubeconform/schema-bundle/,examples/kubeconform/schema-bundle/CRDs-catalog/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'

.PHONY: test-kubeconform
test-kubeconform:
	rm -rf tmp-results
	#kpt fn source examples/kubeconform/manifests | kpt fn eval - --results-dir tmp-results --truncate-output=false $(KUBECONFORM) -- ignore_missing_schemas=true kubernetes_version=1.29.1 schema_locations=$(KUBECONFORM_SCHEMA_LOCATIONS) > test-out.txt || true
	kpt fn source examples/kubeconform/manifests | kpt fn eval - --results-dir tmp-results --truncate-output=false $(KUBECONFORM) -- schema_locations=$(KUBECONFORM_SCHEMA_LOCATIONS) debug=true > test-out.txt || true
	make test-kubeconform-results

.PHONY: test-kubeconform-w-container
test-kubeconform-w-container:
	rm -rf tmp-results
	kpt fn source examples/kubeconform/manifests | kpt fn eval - --results-dir tmp-results --truncate-output=false -i $(KUBECONFORM_IMAGE) -- ignore_missing_schemas=true schema_locations=$(KUBECONFORM_SCHEMA_LOCATIONS) > test-out.txt || true
	make test-kubeconform-results

.PHONY: test-kubeconform-results
test-kubeconform-results:
	grep -e '.* /data/nested: expected string or null, but got object' tmp-results/results.yaml
	grep -e '.* name: invalid-nested-dict' tmp-results/results.yaml
	grep -e '.* /data/a-number: expected string or null, but got number' tmp-results/results.yaml
	grep -e '.* name: invalid-non-string-value' tmp-results/results.yaml

LOCAL_PACKAGES_DIR ?= /tmp/package-compositor

.PHONY: test-package-compositor-e2e
test-package-compositor-e2e: test-package-compositor test-package-compositor-ref
	# We don't set all annotations and comments exactly as kpt
	if [ "$(shell diff -rw fn-output/fleet-1/example-fleet example-fleet-ref | wc -l)" != "40" ]; then echo "*** source-package diff not as expected"; exit 1; fi

.PHONY: test-package-compositor
test-package-compositor:
	rm -rf tmp-results fn-output
	kpt fn source examples/package-compositor/specs | kpt fn eval - --results-dir tmp-results --truncate-output=false $(PACKAGE_COMPOSITOR) | kpt fn sink fn-output
	kpt pkg tree fn-output
	tree fn-output

.PHONY: test-package-compositor-ref
test-package-compositor-ref:
	# This is identical to 'examples/package-compositor/specs/fleet-1/packages.yaml'
	rm -rf example-fleet-ref && mkdir -p example-fleet-ref/olo
	kpt pkg get https://github.com/krm-functions/catalog.git/examples/package-compositor/pkg1 example-fleet-ref/foo --for-deployment
	kpt pkg get https://github.com/krm-functions/catalog.git/examples/package-compositor/pkg2 example-fleet-ref/bar --for-deployment
	kpt pkg get https://github.com/krm-functions/catalog.git/examples/package-compositor/pkg3 example-fleet-ref/bar/baz1 --for-deployment
	kpt pkg get https://github.com/krm-functions/catalog.git/examples/package-compositor/pkg1 example-fleet-ref/bar/baz2 --for-deployment
	kpt pkg get https://github.com/krm-functions/catalog.git/examples/package-compositor/pkg4 example-fleet-ref/olo/baz --for-deployment

.PHONY: test-set-labels
test-set-labels:
	rm -rf tmp-results fn-output
	kpt fn source examples/set-labels | kpt fn eval - --truncate-output=false $(SET_LABELS) -- l1=v1 l2=v2 | kpt fn sink fn-output
	if [ $(shell cat fn-output/deployment.yaml | yq '.metadata.labels.l1|contains("v1")') != "true" ]; then exit1; fi
	rm -rf tmp-results fn-output
	kpt fn source examples/set-labels | kpt fn eval - --truncate-output=false $(SET_LABELS) --fn-config example-function-configs/set-labels/configmap.yaml | kpt fn sink fn-output
	if [ $(shell cat fn-output/deployment.yaml | yq '.metadata.labels.foo|contains("bar")') != "true" ]; then exit1; fi
	rm -rf tmp-results fn-output
	kpt fn source examples/set-labels | kpt fn eval - --truncate-output=false $(SET_LABELS) --fn-config example-function-configs/set-labels/setlabels.yaml | kpt fn sink fn-output
	if [ $(shell cat fn-output/deployment.yaml | yq '.metadata.labels.baz|contains("olo")') != "true" ]; then exit1; fi

.PHONY: test-template-kyaml
test-template-kyaml:
	kpt fn source examples/template | kpt fn eval - --truncate-output=false $(TEMPLATE_KYAML) -- someConfig=aTestConfigString > test-out.txt
	kpt fn source examples/template | kpt fn eval - --truncate-output=false $(TEMPLATE_KYAML) > test-out.txt
