APPLY_SETTERS_BIN := bin/linux_amd64/apply-setters
DIGESTER_BIN := bin/linux_amd64/digester
HELM_RENDER_BIN := bin/linux_amd64/render-helm-chart
HELM_SOURCE_BIN := bin/linux_amd64/source-helm-chart
HELM_UPGRADER_BIN := bin/linux_amd64/helm-upgrader
BASELINE_RENDER_HELM_CHART := gcr.io/kpt-fn/render-helm-chart:v0.2.2

e2e-tests: test-render-helm-chart render-helm-chart-example render-helm-chart-example2 test-source-helm-chart test-helm-upgrader test-apply-setters test-digester

# BEWARE: These tests are fragile - we want to test upgrades, but without upgrade-constraints tests might fail when charts are updated
.PHONY: test-helm-upgrader
test-helm-upgrader:
	kpt fn source examples/helm-upgrader --fn-config example-function-configs/config-upgrade-helm-version-inline.yaml | $(HELM_UPGRADER_BIN) > test-out.yaml
	grep -e '.*upgrade-available: .*cert-manager:v1.8.2' test-out.yaml
	grep -e '.*upgrade-available.0: .*cert-manager:v1.12.1' test-out.yaml
	grep -e '.*upgrade-available.0: .*metacontroller-helm:v4.10.0' test-out.yaml
	grep -e '.*upgrade-available.0: .*karpenter:0.35.0' test-out.yaml
	grep -e '.*upgrade-available.1: .*/external-secrets:0.9.13' test-out.yaml
	rm test-out.yaml

.PHONY: test-render-helm-chart
test-render-helm-chart:
	# For reference, render chart using baseline function
	rm -rf rendered-output
	echo "" | kpt fn eval - --network --fn-config examples/render-helm-chart2/argo-workflows.yaml -i ${BASELINE_RENDER_HELM_CHART} | kpt fn sink rendered-output
	# Source step, fetch chart from upstream, but do not render
	rm -rf sourced-output
	kpt fn source examples/render-helm-chart2 | kpt fn eval - --exec ${HELM_RENDER_BIN} --results-dir results2 | kpt fn sink sourced-output
	grep -e 'message: sourcing with render-helm-chart is deprecated' results2/results.yaml
	# Render from previously sourced chart
	rm -rf rendered-output2
	kpt fn source sourced-output | kpt fn eval - --exec ${HELM_RENDER_BIN} | kpt fn sink rendered-output2
	diff -q rendered-output rendered-output2
	rm -rf rendered-output sourced-output rendered-output2 results2

# Example usage from docs/render-helm-chart.md
.PHONY: render-helm-chart-example
render-helm-chart-example:
	kpt fn source examples/render-helm-chart | kpt fn eval - --exec ${HELM_SOURCE_BIN} | kpt fn sink my-cert-manager-package
	grep -q 'apiVersion: experimental.helm.sh/v1alpha1' my-cert-manager-package/cert-manager-chart.yaml
	cp examples/render-helm-chart/Kptfile my-cert-manager-package/
	kpt fn render my-cert-manager-package -o stdout | grep -q 'team-name: blue-team'
	rm -rf my-cert-manager-package

.PHONY: render-helm-chart-example2
render-helm-chart-example2:
	kpt fn source examples/render-helm-chart/non-stardard-tar-filename | kpt fn eval - --exec ${HELM_RENDER_BIN} | kpt fn sink my-non-stardard-tar-filename
	rm -rf my-non-stardard-tar-filename

.PHONY: test-source-helm-chart
test-source-helm-chart:
	kpt fn source examples/render-helm-chart3 | kpt fn eval - --truncate-output=false --exec $(HELM_SOURCE_BIN) > test-out.yaml
	grep -e 'experimental.helm.sh/chart-sum/karpenter' test-out.yaml
	grep -e 'experimental.helm.sh/chart-sum/cert-manager' test-out.yaml
	rm test-out.yaml

.PHONY: test-apply-setters
test-apply-setters:
	kpt fn source examples/apply-setters | kpt fn eval - --truncate-output=false --exec $(APPLY_SETTERS_BIN) --fn-config example-function-configs/apply-setters/cm-setters.yaml | kpt fn eval - -i gcr.io/kpt-fn/remove-local-config-resources:v0.1.0 -o unwrap > test-out.yaml
	grep -e 'foo: "valueFoo"' test-out.yaml
	grep -e 'bar: "valueBar"' test-out.yaml
	grep -e 'baz: "valueBaz"' test-out.yaml
	grep -e 'replicas: "4"' test-out.yaml
	grep -e 'app.kubernetes.io/version: "a1b2c3d4e5e6"' test-out.yaml
	rm test-out.yaml

.PHONY: test-digester
test-digester: test-digester-step1 test-digester-step3

.PHONY: test-digester-step1
test-digester-step1:
	rm -rf digester-tmp0
	kpt fn source examples/digester | kpt fn eval - --truncate-output=false --exec $(HELM_SOURCE_BIN) | kpt fn sink digester-tmp0

.PHONY: test-digester-step2
test-digester-step2:
	kpt fn source digester-tmp0 | kpt fn eval - --truncate-output=false --exec $(DIGESTER_BIN) > test-out.yaml
	head -n 60 test-out.yaml

.PHONY: test-digester-step3
test-digester-step3:
	rm -rf digester-tmp1
	kpt fn source digester-tmp0 | kpt fn eval - --truncate-output=false --exec $(DIGESTER_BIN) | kpt fn sink digester-tmp1
	kpt fn render digester-tmp1 -o unwrap > test-out.yaml
	grep 'image:' test-out.yaml


SOURCE_HELM_CHART_IMAGE ?= ghcr.io/krm-functions/source-helm-chart@sha256:abdbfee8c27175925ace219e945c03fab170733ed1b9a84577cd92a634c3668d
DIGESTER_IMAGE ?= ghcr.io/krm-functions/digester@sha256:e8f3ea2ebcf662d8e70eed477d5d9b9e99be0a6773582fe8cd6b2e79fa74242d

.PHONY: test-digester-w-containers
test-digester-w-containers:
	echo "** sourcing step"
	rm -rf cert-manager-package
	kpt fn source examples/digester \
	  | kpt fn eval - --network -i $(SOURCE_HELM_CHART_IMAGE) \
	  | kpt fn eval - --network --truncate-output=false -i $(DIGESTER_IMAGE) \
	  | kpt fn sink cert-manager-package
	echo "** rendering using pipeline in Ktfile"

.PHONY: test-digester-w-containers2
test-digester-w-containers2:
	rm -rf cert-manager-rendered
	kpt fn render cert-manager-package -o stdout | kpt fn sink cert-manager-rendered
