name: Build and sign multi-arch container

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'Makefile.test'
      - 'catalog.json'
      - 'scripts/**'
      - 'docs/**'
      - 'examples/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Build schema bundle for kubeconform
      run: |
        scripts/source-schemas.sh

    - name: Build containers
      run: make all-container

    - name: Log in to the Container registry
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push containers
      run: make manifest-list | tee manifest.log

    - uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # tag=v4.1.0

    - name: Sign container
      run: make manifest-list-sign

    - name: Update catalog
      run: scripts/update-image-digest-in-docs.sh

    - name: Create catalog update PR
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
        token: ${{ github.token }}
        commit-message: 'Update catalog for build ${{ github.sha }}'
        title: 'Update catalog.json for build ${{ github.sha }}'
        body: |
          Update catalog.json after release of build ${{ github.sha }}
        #labels: automated pr
        branch: catalog/update
        delete-branch: true
        add-paths: catalog.json
